version: '3.8'

services:
  auction-api:
    build:
      context: ./SmartPepper-Auction-Blockchain-System/backend
    ports:
      - "80:3002"
    environment:
      - NODE_ENV=production
    env_file:
      - ./SmartPepper-Auction-Blockchain-System/backend/.env
